version: '3.8'

services:
    api:
        container_name: go-gcp_api
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
